//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investrosite.Models.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter your Name"), MaxLength(30), MinLength(2)]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter Email"), MaxLength(30)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Enter a valid email.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter Phone"), MinLength(11), MaxLength(11)]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please enter Password"), MaxLength(15), MinLength(4)]
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
