//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investrosite.Models.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Report
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter your Name"), MaxLength(30), MinLength(2)]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter Email"), MaxLength(30)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Enter a is valid email.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your issue"), MaxLength(30), MinLength(10)]
        public string Issue { get; set; }
    }
}
